## NBDAの基礎 {#s5-2}    
### 基本的なモデル    
最も基本的なNBDAは以下のような式で表される(式\@ref(eq:NBDA))。なお、$N$は集団内の個体数を表し、$i = 1,2,\dots,N$、$j = 1,2,\dots,N$は各個体を表す添え字である。$t$は時間を表し、連続的な時間を表す値(e.g., 経過時間や日数)でも学習した順番を表す値でもよい。      

- $\lambda_i(t)$: 個体$i$が時点$t$において行動を学習する確率(生存時間解析のハザード率に相当)    
- $\lambda_0(t)$: 学習する確率が時間と共にどのように変化するかを決定するベースライン関数。時点$t$において非社会的学習する確率を表す。NBDAの種類によって異なる関数が仮定される。          
- $z_i(t)$: 個体$i$が時点$t$において行動を学習しているか否かを表す(1: 学習済, 0: 未学習)。    
- $a_{ij}$: 社会ネットワーク上の個体$i$と$j$のつながりの強さ  
- $s$: 非社会的学習に比べて社会的学習の強さがどの程度強いかを表す定数  

$$
\lambda_i(t) = \lambda_0(t)(1 - z_i(t)) \Bigl(s \Sigma_{j = 1}^N a_{ij}z_j(t) + 1 \Bigl) (\#eq:NBDA)  
$$

まだ学習していない個体が時点$t$において行動を社会的に学習する確率は、$\Sigma_{j = 1}^N a_{ij}z_j(t)$に比例する。つまり、$s = 0$のとき学習は全て非社会的に起こることを表す。  

### NBDAに用いる社会ネットワーク  
#### どのような種類の社会ネットワークを用いるべきか  
NBDAの$s$パラメータは、どのような社会ネットワークを$a_{ij}$に用いるかによって解釈が異なるが、どのようなネットワークを用いるのが適切かは、リサーチクエスチョンによっても変わる。例えば、社会的学習は近接している個体のみから影響を受けると仮定すると、NBDAでは近接関係を表すネットワークを使用するのが望ましい。このとき、「近接している」とみなす距離は対象とする種の個体がそれ以上離れたら社会的に学習できなくなる距離を設定すべきである[@Hoppitt2017]。もし、社会的学習が何らかの社会的交渉(e.g., 毛づくろい)中に生じると想定されるのであれば、その社会交渉のネットワークを用いるのがよいだろう。  

NBDAでは、どのようなネットワークが適切かということを、複数のネットワークを用いたモデルを作成し、どのネットワークの予測が最も優れているかを比較することで検討することもできる(e.g., AICなどを用いる)。また、複数のネットワークを用いた結果を比較することで、社会鉄伝達がどのようなメカニズムで生じているのかを推測することもできる。例えば、 @Kulahci2016 は複数種類のネットワークを用いてカラスの社会的学習について分析を行い、敵対的行動や近接関係のネットワークではなく、親和的行動のネットワークが最もよくカラスの社会的伝達を予測できることを示した。この結果から、Kulahciらは十分に近づけるほど親和的な関係をもつ個体同士で社会的伝達が起こっていたのではないかと考察している。     

#### 行動頻度で重みづける  
式\@ref(eq:NBDA)の基本的なモデルでは行動をすでに学習した個体$j$から受ける影響は、社会ネットワーク上のつながり$a_{ij}$のみに依存し、その個体がどの程度その行動を行うかには依存しないと仮定されている。しかし、行動頻度が高い個体からの方が、低い個体からよりも社会的学習が生じやすいと考える方が妥当であることもある。その場合、式\@ref(eq:NBDA)の$a_{ij}$を行動頻度$W_j$で重みづけて$a_{ij}W_j$とすることで、相手個体の行動頻度も考慮することができる。  

#### 動的なネットワーク  
式\@ref(eq:NBDA)の基本的なモデルでは、社会ネットワークはずっと同じであることを仮定している。しかし、順位変動や個体の移出入によって社会ネットワークの構造が途中で大きく変化することは十分に考えられる。このような問題に対処するため、NBDAでは時間的に変化するネットワークを用いて分析を行うこともできる[c.f., @Hobaiter2014]。このとき、モデル式は以下のようになる(式\@ref(eq:NBDA2))。$a_{ij}$が$a_{ij}(t)$となり、個体$i$と$j$の社会的つながりが時間的に変化することが表されている。$a_{ij}(t)$は$t$時点における個体$i$と$j$の社会的つながりである。      

$$
\lambda_i(t) = \lambda_0(t)(1 - z_i(t)) \Bigl(s \Sigma_{j = 1}^N a_{ij}(t) z_j(t) + 1 \Bigl) (\#eq:NBDA2)  
$$

ただし、社会交渉やassociationのデータを用いた動的なネットワークを作成する場合には、各期間において十分なデータがあるか注意する必要がある。データ数が少なすぎると、サンプリングエラーの影響が大きなり、精度が低くなってしまう。一方で、**観察ネットワーク**(個体$i$が個体$j$が行動するのを観察した回数を表すネットワーク)を使用する場合には、通常は動的なネットワークを使用するのが望ましい。この場合、$a_{ij}(t)$は$t$時点までに個体$j$の行動を個体$i$が観察した回数になる。このようなデータは、通常実験環境下や行動が特定の場所で行われる場合(c.f., @Hobaiter2014)に収集可能である。  


