# 社会ネットワーク分析の概説 {#c1} 

## 社会ネットワーク分析(SNA)とは    
**社会ネットワーク**とは，相互に社会的なつながりをもつ個体の集まりのことを指す[@Krause2015]。多くの生物において、集団を構成する個体たちはランダムランダム・均一に他個体と関わりあっているわけではなく、その関係の強度やタイプ、ダイナミクスは非常に多様である。社会ネットワークは、このような多様な関係によって構成されている[@Croft2019]。 


霊長類のように多くの個体が集団生活を行う種においては、個体の行動は一対一の社会関係だけではなく、集団全体の関係構造(e.g., 誰と誰がどのような関係を持つか)に強く影響を受ける[@Croft2019; @Krause2015]。例えば、個体$A$が個体$B$に対してどのような行動をとるのかには、個体$A$と$B$がそれぞれ誰とどのようなな関係を持つかや、その関係の強度が大きく影響するだろう。また社会ネットワークの構造は、こうした個体の行動の集積を通じて、集団の土地利用パターンや疾病・情報の伝播、離合集散パターンなど集団レベルの現象に対しても影響を与える。以上のように、集団で生活する種を対象に研究を行う際には、その背後にある社会ネットワークについて理解することで、一対一の関係のみに着目するよりもはるかに多くのことを理解できる[@Sueur2011; @Krause2015]。  

**社会ネットワーク分析（SNA: Social Network Analysis）**とは、集団内の2個体間の社会関係に基づいて社会ネットワークを描写することで、その社会関係の構造や構成個体の特性を調べる分析手法のことである[@Croft2019; @Krause2015]。SNAの手法を用いることで、社会ネットワークの構造が個体の行動や集団レベルの現象に与える影響を検討することが可能になる。  

近年、動物行動学や霊長類でもSNAの手法を用いた研究が増加している[@Sueur2011; @Puga2019]。
例えば、SNAを用いた霊長類の研究には以下のようなものがある。  

- オス間の親和的交渉のネットワークが移籍の成否や繁殖成功に与える影響を調べた研究[@Gilby2013; @Kawazoe2019]  
- メス間の親和的交渉のネットワークがメスの適応度に与える影響を調べた研究[@Lehmann2016; @Cheney2016]  
- 毛づくろいネットワークが寄生虫への感染に与える影響を調べた研究[@MacIntosh2012; @Duboscq2016]   
- 社会ネットワークが行動の社会的伝達に与える影響を検討した研究[@Hobaiter2014; @Canteloup2020]  
- 異なる行動指標のネットワーク間の関連を調べた研究[@Shimada2018; @Campbell2018]  
- 種間のネットワークを比較した研究[@Sueur2011b; @Bala2018]   
